### ISSUE TITLE
sigmoid function accepts only single numbers or matrices of dimensions m*1

### ISSUE THREAD

**Issue by rohithpr** [rohithpr/PyML#1]
It should accept multidimensional matrices and matrices of dimensions 1*m

**Comment by Franky12** [comment]
Hi rohithpr ,
Want to contribute to this project . I am a decent programmer but new to open source contribution.
Little guidance from you could be helpful at times .If I can get your email-id so that I can contact you.

**Comment by rohithpr** [comment]
@Franky12 - You can join the room [here](https://gitter.im/rohithpr/PyML) for any conversation.

This issue itself has been resolved by #6. Take a look at the code base, it's pretty small! Let me know if you need help with anything.
