### ISSUE TITLE
Naming conflict with older project

### ISSUE THREAD

**Issue by ralphm** [rohithpr/PyML#7]
Hi. I just noticed this project when I tried to install a different, much older, project named [PyML](http://pyml.sourceforge.net/) as a dependency for [talon](https://github.com/mailgun/talon) and ended up with a entirely different package than I expected. Likely because your project is now on PyPI and the other one isn't.

Are you aware of this naming conflict? Since your project is still pretty young, I was wondering if renaming is an option for you.

**Comment by rohithpr** [comment]
I have removed the project from PyPI for now. I will figure out the other changes later. Guess this is enough to solve most issues. Thank you.
